### ISSUE TITLE
Cursor navigation

### ISSUE THREAD

**Issue by haudan** [LukasKalbertodt/term-painter#21]
Would cursor navigation be a sensible addition to this library, or would this be out of scope / a nonfeature?
I think it would be great, since it would make this the only crate with both platform independent terminal colors and movement (that I am aware of).

I'm willing to implement it for both Windows and ANSI terminals, all I need is the consent.

**Comment by LukasKalbertodt** [comment]
Hi! I don't know too much about cursor movement and jazz like that (especially so for Windows terminals), but I don't really think that it would fit into the scope of this library. Sorry! Let's rather narrow down the focus of this library to just *formatting* and *coloring* of text. 

You could simply write your own crate for now :-)

**Comment by haudan** [comment]
Alrigh, writing my own crate it is!
I'll let you know when it's ready, maybe you'd like to try it out.

**Comment by haudan** [comment]
Alright here it is! **[term_cursor](https://github.com/Lisoph/term_cursor)** 🎉 

I have just pushed the initial, alpha release of my term_cursor crate. Haven't added a readme yet. It also isn't hosted on crates.io nor docs.rs yet. But that's all going to follow in a few days!

Builds and runs under Windows and Linux (possibly more, not tested). Try running the `window` example => `cargo run --example window`.

The doc should be good enough to give you an idea of how to use it!
I recommend cloning it locally and building the doc yourself (`cargo doc`), since it's not hosted yet.

Cheers!

@LukasKalbertodt
