### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by phideg** [LukasKalbertodt/term-painter#23]
Today clippy showed me following error:

```shell
error: multiple versions for dependency `cfg-if`: 0.1.10, 1.0.0
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_crate_versions
```

traversing the dependency graph I noticed that the problems stems from the `term-painter` crate still using version `0.6.1` of the `term` crate. 

```shell
├── term-painter v0.3.0
│   └── term v0.6.1
│       └── dirs v2.0.2
│           ├── cfg-if **v0.1.10**
```

Would it be possible to upgrade to version `0.7` of the term crate?

**Comment by LukasKalbertodt** [comment]
Updated to term 0.7, released as term-painter 0.4.
